name: manual-build

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: /github #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: 

      - name: Echo Version
        run: |
          make getversion

      - name: Build and push containers
        run: |
          export SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
          aws ecr login
          make push
